// ============================================================
//  lng2cpp -- IPv4OctetSort language-pack embedder (build tool)
//
//  Usage: lng2cpp <out.cpp> <langdir>
//
//  Scans <langdir>\\*.lng (sorted by file name for deterministic
//  output) and writes a C++ source that defines ui::kEmbeddedLanguages,
//  so the .lng files ship inside the exe without any manual code edits.
//
//  Exit code 0 on success; 1 on any failure (no output written).
// ============================================================
#include <windows.h>

#include <algorithm>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace {

struct SourceFile {
    std::wstring stem;    // file name without extension
    std::string content;  // raw bytes
};

bool ReadFile(const std::wstring& path, std::string* content) {
    std::ifstream file(path.c_str(), std::ios::binary);
    if (!file) return false;
    std::ostringstream buffer;
    buffer << file.rdbuf();
    *content = buffer.str();
    return true;
}

// Collects <dir>\\*.lng sorted by stem (wcscmp) for deterministic output.
bool CollectLanguageFiles(const std::wstring& dir, std::vector<SourceFile>* out) {
    const std::wstring pattern = dir + L"\\*.lng";
    WIN32_FIND_DATAW found = {};
    const HANDLE search = FindFirstFileW(pattern.c_str(), &found);
    if (search == INVALID_HANDLE_VALUE) {
        if (GetLastError() == ERROR_FILE_NOT_FOUND) return true;  // empty dir is allowed
        return false;
    }
    do {
        if ((found.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) != 0) continue;
        const std::wstring name = found.cFileName;
        const size_t dot = name.find_last_of(L'.');
        const std::wstring stem = (dot == std::wstring::npos) ? name : name.substr(0, dot);

        SourceFile item;
        item.stem = stem;
        if (!ReadFile(dir + L"\\" + name, &item.content)) {
            FindClose(search);
            return false;
        }
        out->push_back(item);
    } while (FindNextFileW(search, &found) != 0);
    FindClose(search);

    std::sort(out->begin(), out->end(),
              [](const SourceFile& a, const SourceFile& b) { return wcscmp(a.stem.c_str(), b.stem.c_str()) < 0; });
    return true;
}

// Stems must be pure ASCII (they become C string literals).
bool IsAsciiPrintable(const std::wstring& text) {
    for (size_t i = 0; i < text.size(); ++i) {
        if (text[i] < 0x21 || text[i] > 0x7E) return false;
    }
    return !text.empty();
}

void WriteByteArray(FILE* out, const char* symbol, const std::string& bytes) {
    std::fprintf(out, "const unsigned char %s[] = {", symbol);
    for (size_t i = 0; i < bytes.size(); ++i) {
        if (i % 16 == 0) std::fprintf(out, "\n    ");
        std::fprintf(out, "%u,", static_cast<unsigned char>(bytes[i]));
    }
    std::fprintf(out, "\n};\n");
}

std::string Narrow(const std::wstring& wide) {
    std::string out;
    for (size_t i = 0; i < wide.size(); ++i) {
        out += static_cast<char>(wide[i] & 0x7F);
    }
    return out;
}

}  // namespace

int wmain(int argc, wchar_t** argv) {
    if (argc != 3) {
        std::fprintf(stderr, "usage: lng2cpp <out.cpp> <langdir>\n");
        return 1;
    }

    std::vector<SourceFile> files;
    if (!CollectLanguageFiles(argv[2], &files)) {
        std::fprintf(stderr, "lng2cpp: cannot scan directory\n");
        return 1;
    }
    if (files.empty()) {
        std::fprintf(stderr, "lng2cpp: no .lng files found\n");
        return 1;
    }
    for (size_t i = 0; i < files.size(); ++i) {
        if (!IsAsciiPrintable(files[i].stem)) {
            std::fprintf(stderr, "lng2cpp: file name must be printable ASCII\n");
            return 1;
        }
    }

    FILE* out = nullptr;
    if (_wfopen_s(&out, argv[1], L"w") != 0 || out == nullptr) {
        std::fprintf(stderr, "lng2cpp: cannot open output file\n");
        return 1;
    }

    std::fprintf(out,
                 "// Auto-generated by tools/lng2cpp.cpp from languages/*.lng.\n"
                 "// Do not edit; re-run the build to regenerate.\n"
                 "#include \"ui/embedded_languages.h\"\n\n"
                 "namespace {\n");
    for (size_t i = 0; i < files.size(); ++i) {
        char symbol[64] = {0};
        std::snprintf(symbol, sizeof(symbol), "kLngData%u", static_cast<unsigned int>(i));
        WriteByteArray(out, symbol, files[i].content);
    }
    std::fprintf(out, "}  // namespace\n\n");

    std::fprintf(out, "const ui::EmbeddedLanguage ui::kEmbeddedLanguages[] = {\n");
    for (size_t i = 0; i < files.size(); ++i) {
        char symbol[64] = {0};
        std::snprintf(symbol, sizeof(symbol), "kLngData%u", static_cast<unsigned int>(i));
        std::fprintf(out, "    { \"%s\", %s, sizeof(%s) },\n", Narrow(files[i].stem).c_str(), symbol,
                     symbol);
    }
    std::fprintf(out, "};\n");
    std::fprintf(out, "const unsigned int ui::kEmbeddedLanguageCount = %u;\n",
                 static_cast<unsigned int>(files.size()));

    std::fclose(out);
    return 0;
}
